alias ls='ls -F'
alias ll='ls -lh'
alias update='sudo apt-get update && sudo apt-get upgrade'
alias open='explorer.exe'
alias sqlstart='sudo service postgresql start'
alias start_sql='sudo service postgresql start'
alias start_postgres='sudo service postgresql start'
alias cd..='cd ..'
